let products=JSON.parse(localStorage.getItem("be_products")||"[]"),cats=JSON.parse(localStorage.getItem("be_cats")||"[]"),orders=JSON.parse(localStorage.getItem("be_orders")||"[]"),editId=null,newImage="";
const euro=n=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"}),persist=()=>{localStorage.setItem("be_products",JSON.stringify(products));localStorage.setItem("be_cats",JSON.stringify(cats));localStorage.setItem("be_orders",JSON.stringify(orders));renderAll()};
function showPanel(id,btn){document.querySelectorAll(".admin-panel").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".sidebar button").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}
function renderAll(){const sales=orders.reduce((s,o)=>s+o.total,0),units=orders.length?orders.length:0;aSales.textContent=euro(sales);aOrders.textContent=orders.length;aTicket.textContent=euro(orders.length?sales/orders.length:0);aCustomers.textContent=new Set(orders.map(o=>o.email)).size;aSold.textContent=units;salesBig.textContent=euro(sales);salesChart.innerHTML=[18,30,24,48,40,62,54,78,68,90].map(h=>`<i style="height:${h}%"></i>`).join("");categoryStats.innerHTML=cats.map(c=>`<p><span>${c}</span><b>${euro(orders.filter(o=>o.cat===c).reduce((s,o)=>s+o.total,0))}</b></p>`).join("");recentOrders.innerHTML=orders.length?orders.slice(-5).reverse().map(o=>`<div class="tr"><span>#${o.id}</span><span>${o.customer}</span><b>${euro(o.total)}</b><span>${o.status}</span></div>`).join(""):'<div class="empty">Todavía no hay pedidos.</div>';ordersTable.innerHTML=orders.length?orders.slice().reverse().map(o=>`<div class="tr"><span>#${o.id}</span><span>${o.date}</span><span>${o.customer}</span><b>${euro(o.total)}</b><span>${o.status}</span></div>`).join(""):'<div class="empty">Todavía no hay pedidos.</div>';productAdminList.innerHTML=products.map(p=>`<div class="item"><div><b>${p.name}</b><small>${p.cat} · ${euro(p.price)}</small></div><div><button class="secondary" onclick="openProductEditor(${p.id})">Editar</button><button class="danger" onclick="deleteProduct(${p.id})">Eliminar</button></div></div>`).join("");categoryAdminList.innerHTML=cats.map((c,i)=>`<div class="item"><b>${c}</b><button class="danger" onclick="deleteCategory(${i})">Eliminar</button></div>`).join("")}
function openProductEditor(id=null){editId=id;newImage="";productEditor.classList.remove("hidden");pCategory.innerHTML=cats.map(c=>`<option>${c}</option>`).join("");const p=id?products.find(x=>x.id===id):null;editorTitle.textContent=id?"Editar producto":"Añadir producto";pName.value=p?.name||"";pPrice.value=p?.price||"";pOld.value=p?.old||"";pCategory.value=p?.cat||cats[0];pDesc.value=p?.desc||"";pPreview.innerHTML=p?.img?`<img src="${p.img}">`:""}
function closeProductEditor(){productEditor.classList.add("hidden")}pImage.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{newImage=r.result;pPreview.innerHTML=`<img src="${newImage}">`};r.readAsDataURL(f)}
function generateDescription(){pDesc.value=`${pName.value} práctico y versátil para el hogar, pensado para el uso diario y con un diseño funcional.`}
function saveProduct(){if(!pName.value||!pPrice.value)return alert("Completa nombre y precio.");const data={name:pName.value,price:Number(pPrice.value),old:Number(pOld.value)||null,cat:pCategory.value,desc:pDesc.value,img:newImage||"https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=700&q=80"};if(editId)products=products.map(p=>p.id===editId?{...p,...data,img:newImage||p.img}:p);else products.unshift({id:Date.now(),...data});persist();closeProductEditor()}
function deleteProduct(id){if(confirm("¿Eliminar este producto?")){products=products.filter(p=>p.id!==id);persist()}}function newCategory(){const c=prompt("Nombre de la nueva categoría");if(c&&c.trim()&&!cats.includes(c.trim())){cats.push(c.trim());persist()}}function deleteCategory(i){if(confirm("¿Eliminar categoría?")){cats.splice(i,1);persist()}}function clearOrders(){if(confirm("¿Borrar pedidos demo?")){orders=[];persist()}}function saveStore(){localStorage.setItem("be_store",JSON.stringify({name:storeName.value,address:storeAddress.value,phone:storePhone.value,hours:storeHours.value}));alert("Cambios guardados")}
storeName.value="Bazar El Escándalo";storeAddress.value="C/ Toledo, 25 · 13003 Ciudad Real";storeHours.value="L-V 09:00–13:30 / 16:00–20:00\nSábados 09:00–13:30";renderAll();