const seed=[{id:1,name:"Cesta de mimbre",price:12.90,old:15.90,cat:"Organización",desc:"Cesta decorativa y práctica para organizar el hogar.",img:"https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=700&q=80"},{id:2,name:"Kit de limpieza",price:8.50,old:null,cat:"Limpieza",desc:"Todo lo necesario para una limpieza cómoda y rápida.",img:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=700&q=80"},{id:3,name:"Lámpara de mesa",price:25,old:null,cat:"Decoración",desc:"Lámpara de mesa elegante para cualquier estancia.",img:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80"},{id:4,name:"Planta decorativa",price:7.50,old:null,cat:"Jardín",desc:"Un toque verde para tu hogar.",img:"https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=700&q=80"},{id:5,name:"Alfombra de yute",price:19.90,old:null,cat:"Hogar",desc:"Alfombra de fibra natural para crear ambientes cálidos.",img:"https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=700&q=80"}];
let products=JSON.parse(localStorage.getItem("be_products")||"null")||seed,cats=JSON.parse(localStorage.getItem("be_cats")||"null")||["Hogar","Decoración","Limpieza","Jardín","Organización","Ofertas"],cart=JSON.parse(localStorage.getItem("be_cart")||"[]"),orders=JSON.parse(localStorage.getItem("be_orders")||"[]");
const euro=n=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"});const save=()=>{localStorage.setItem("be_products",JSON.stringify(products));localStorage.setItem("be_cats",JSON.stringify(cats));localStorage.setItem("be_cart",JSON.stringify(cart));localStorage.setItem("be_orders",JSON.stringify(orders))};
function renderProducts(){const q=(document.getElementById("search")?.value||"").toLowerCase();let a=products.filter(p=>(p.name+" "+p.cat+" "+p.desc).toLowerCase().includes(q));document.getElementById("products").innerHTML=a.map(p=>`<article class="product"><img src="${p.img}"><div><small>${p.cat}</small><h3>${p.name}</h3><p>${p.desc}</p><b>${euro(p.price)}</b>${p.old?`<del>${euro(p.old)}</del>`:""}<button onclick="addCart(${p.id})">Añadir al carrito</button></div></article>`).join("");document.getElementById("cats").innerHTML=cats.map(c=>`<button onclick="filterCategory('${c}')">${c}<small>Ver productos</small></button>`).join("")}
function filterCategory(c){document.getElementById("search").value=c;renderProducts();document.getElementById("productos").scrollIntoView()}
function addCart(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();updateBadge();openCart()}
function updateBadge(){document.getElementById("cartBadge").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function cartTotal(){return cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0)}
function openCart(){document.getElementById("cartModal").classList.remove("hidden");renderCart()}
function closeCart(){document.getElementById("cartModal").classList.add("hidden")}
function renderCart(){const box=document.getElementById("cartLines");if(!cart.length){box.innerHTML='<div class="empty">Tu carrito está vacío.</div>';document.getElementById("cartSummary").innerHTML="";return}box.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id),s=p.price*x.qty;return `<div class="cart-line"><img src="${p.img}"><div><b>${p.name}</b><small>${euro(p.price)}</small><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${p.id},1)">+</button><button class="remove" onclick="removeCart(${p.id})">Eliminar</button></div></div><strong>${euro(s)}</strong></div>`}).join("");const total=cartTotal();document.getElementById("cartSummary").innerHTML=`<div class="summary"><span>Subtotal</span><b>${euro(total)}</b></div><div class="summary"><span>Envío</span><b>${total>=50?"Gratis":"4,95 €"}</b></div><div class="summary total"><span>Total</span><b>${euro(total+(total>=50?0:4.95))}</b></div>`}
function changeQty(id,n){const x=cart.find(i=>i.id===id);x.qty+=n;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save();updateBadge();renderCart()}
function removeCart(id){cart=cart.filter(i=>i.id!==id);save();updateBadge();renderCart()}
function openCheckout(){if(!cart.length)return;closeCart();document.getElementById("checkoutModal").classList.remove("hidden");document.getElementById("checkoutTotal").innerHTML=`Total a pagar: <b>${euro(cartTotal()+(cartTotal()>=50?0:4.95))}</b>`}
function closeCheckout(){document.getElementById("checkoutModal").classList.add("hidden")}
function placeOrder(){if(!coName.value||!coEmail.value||!coAddress.value||!coCity.value||!coZip.value)return alert("Completa los datos de entrega.");const id="BE-"+Date.now().toString().slice(-6);orders.push({id,total:cartTotal()+(cartTotal()>=50?0:4.95),customer:coName.value,email:coEmail.value,date:new Date().toLocaleString("es-ES"),status:"Pendiente"});cart=[];save();updateBadge();closeCheckout();alert("Pedido "+id+" creado. La conexión al proveedor de pago real se hará en producción.")}
function openLogin(){document.getElementById("loginModal").classList.remove("hidden")}function closeLogin(){document.getElementById("loginModal").classList.add("hidden")}function showRegister(){document.getElementById("loginView").innerHTML='<span class="eyebrow">MI CUENTA</span><h2>Crear cuenta</h2><label>Nombre<input id="regName"></label><label>Correo<input id="regEmail" type="email"></label><label>Contraseña<input id="regPass" type="password"></label><button class="primary full" onclick="register()">Crear cuenta</button><button class="textbtn" onclick="location.reload()">Volver a iniciar sesión</button>'}function register(){if(!regName.value||!regEmail.value||!regPass.value)return alert("Completa todos los campos.");localStorage.setItem("be_user",JSON.stringify({name:regName.value,email:regEmail.value}));alert("Cuenta creada");closeLogin()}function login(){if(!loginEmail.value||!loginPass.value)return alert("Completa correo y contraseña.");localStorage.setItem("be_user",JSON.stringify({email:loginEmail.value}));alert("Sesión iniciada");closeLogin()}
renderProducts();updateBadge();